version: '3'
services:
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "mysql"
      MYSQL_USER: "root"
    command: mysqld

  elasticsearch:
    image: elasticsearch
    depends_on:
      - mysql

  #kibana:
   # image:kibana
    #ports:
    #  - "5601:5601"
    #environment:
    #  - ELASTICSEARCH_URL = http://elasticsearch:9200/


  rails:
    build: ./railsServer/
    depends_on:
       - elasticsearch

  flask:
    build: ./flaskServer/
    depends_on:
      - rails

  apache1:
    build: ./apache1/
    depends_on:
      - varnish1
      - varnish2
      - flask
     # - kibana

  varnish1:
    build: ./varnish1/
    depends_on:
      - mysql

  apache2:
    build: ./apache2/
    depends_on:
      - varnish1
      - varnish2
      - flask
      #- kibana

  varnish2:
    build: ./varnish2/
    depends_on:
      - mysql

  haproxy:
    build: ./haproxy/
    ports:
      - "80:80"
    depends_on:
      - varnish1
      - varnish2
      - apache1
      - apache2

  dbinitiator:
    build: ./initiator/
    depends_on:
      - haproxy

  node:
    build: ./nodeJSServer/
    ports:
      - "61234:61234"
    depends_on:
      - dbinitiator
